package Rozzies;

public class DNA {

    public static void main(String[] args) {

        String DNA = "CACGGCCGTTTTGCCGCACGATGCTTGTCTGTCTGCGAAATCTTTGCATTTAGAGATAGAGTTACACGGTGTGCGCGCATCCCTTACCCCCAGCGGGTGTTACGACGTTGCAGCGTGCGTTGTAATGTTCGAGCGTTAACATGCCAGATGATCTTGTTTAAGATAGTCGGTCTGGGCAAAATTCATCGATATGATGCGTGCGATGGGGTATGATGGGATCCAGCTGTGACGTAGGTCATGAGCCGGGGCACCAGCCGCACGTTACTGATGGGTTGCAACTTTAGTTGGTCCTACGGGTGGTATCTTTATCGGGGTAACCATCCGAAGCTGAGTGAGAGAATATACATACAATCGTCAGCCGGCGAAAATTCTCAGGATAAAGAATGTTTAACCGATGCTCGTCGCTTGGCTTCAAGTTCTGGATGATAGTAACGACACGTGACGAAAACCTGACACGATTTGACGACTATGACGCACCTCTTAACGAGTTCGGTGGGTCCCCGTGACGTCCTGACGGGAATAAGACGCTACAATCAAACGCGCAGTCTACCGGGACATCCTACGGGATTTTGTCAGCACGCATTCAAATCATTGGAGCGTCCCAGCGCTCTGTGCTCGTTCGTACCTTCCTGACTTCCGCTCTAGGTGGCTCCCCGGGAATCAGTGGTGCGAACATGTCACTCTGGCCTCCGGTCGTCTCACTCTTTCTGTTGTGGTGCAGAACTAGCTTACCAACCCAACAAATTTAGCTCAGGCCTTTAGCGCCGAGCATAGTTTCTGGCTGGAGCTTGTCGTTATGCCGATCGGATCAATGATCGTATCTTTGTGCCGTCTTGGTGCAATACTCCCCCGAATACAGCG\n";

        int length = DNA.length();
        int A = 0, G = 0, T = 0, C = 0;

        for (int r = 0; r < length; r++){
            char chosen = DNA.charAt(r);

            if (chosen == 'A'){A++;};
            if (chosen == 'G'){G++;};
            if (chosen == 'C'){C++;};
            if (chosen == 'T'){T++;};
        }

        System.out.print(A + " ");
        System.out.print(C + " ");
        System.out.print(G + " ");
        System.out.print(T);


        //I LOST ALL MY SHIT


    }

}